apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: accounts.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: Account
    plural: accounts
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - email
            - parentId
            properties:
              email:
                type: string
                description: AWS account email address. Must be unique across all AWS accounts.
              parentId:
                type: string
                description: AWS Organizations parent ID (root or organizational unit) where the account will be created.
              providerConfigName:
                type: string
                description: Management account ProviderConfig used for Organizations operations. Defaults to "default".
                default: default
              managementPolicies:
                type: array
                description: Crossplane management policies propagated to managed resources. Defaults to ["*"].
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"
              policyAttachments:
                type: array
                description: Optional list of Service Control Policy ARNs to attach to the account.
                items:
                  type: string
              tags:
                type: object
                description: "AWS resource tags. Automatically includes {\"hops\": \"true\"}."
                x-kubernetes-preserve-unknown-fields: true
              providerConfig:
                type: object
                description: Configuration for automated ProviderConfig creation. Creates IAM user, access key, and ProviderConfig with assumeRoleChain.
                properties:
                  name:
                    type: string
                    description: Override ProviderConfig name. Defaults to the account name.
                  secretNamespace:
                    type: string
                    description: Namespace for the credentials Secret. Defaults to the Account's namespace.
          status:
            type: object
            properties:
              accountId:
                type: string
              adminRoleArn:
                type: string
              providerConfigName:
                type: string
              iamUserName:
                type: string
              credentialsSecretName:
                type: string
              ready:
                type: boolean
